services:
  pz-gateway:
    container_name: pz-gateway
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    environment:
      - NODE_ENV=development
      - PORT=8000
    volumes:
      - .:/app
      - pz_gateway_node_modules:/app/node_modules

volumes:
  pz_gateway_node_modules:
