services:
  ps-mer-gateway:
    container_name: ps-mer-gateway
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    environment:
      - NODE_ENV=development
      - PORT=8000
    volumes:
      - .:/app
      - ps_mer_gateway_node_modules:/app/node_modules

volumes:
  ps_mer_gateway_node_modules:
