FROM node:20 AS base
WORKDIR /app
COPY package* .
RUN npm i
COPY . .
RUN npm run build

FROM node:20-alpine
WORKDIR /app
COPY package* .
RUN npm i --omit=dev
COPY --from=base /app/dist ./dist
EXPOSE 8000
CMD [ "npm", "run", "start:prod" ]